apiVersion: apps/v1
kind: Deployment
metadata:
    name: workly
    labels:
        app: workly
    annotations:
        kubernetes.io/change-cause: "Initial deployment"
spec:
    replicas: 1
    selector:
        matchLabels:
            app: workly
    template:
        metadata:
            name: workly
            labels:
                app: workly
                env: dev
                app.kubernetes.io/name: workly
        spec:
            containers:
                - name: accountservice
                  image: accountservice
                  ports:
                      - containerPort: 80
                  env:
                      - name: ASPNETCORE_ENVIRONMENT
                        value: "Development"
                      - name: ASPNETCORE_URLS
                        value: "http://+:80"
                      - name: ConnectionStrings__DefaultConnection
                        value: "Server=AcountDb;Port=5432;Database=accountdb;Username=postgres;Password=postgres;"
                      - name: MongoDbSettings__ConnectionString
                        value: "mongodb://MongoDb"
                - name: company-svc
                  image: companysvc
                  ports:
                      - containerPort: 80
                  env:
                      - name: ASPNETCORE_ENVIRONMENT
                        value: "Development"
                      - name: ASPNETCORE_URLS
                        value: "http://+:80"
                      - name: MongoDbSettings__ConnectionString
                        value: "mongodb://MongoDb"
                      - name: RabbitMq__Host
                        value: "rabbitmq"
                - name: vacancy-service
                  image: vacancyservice
                  ports:
                        - containerPort: 80
                  env:
                      - name: ASPNETCORE_ENVIRONMENT
                        value: "Development"
                      - name: ASPNETCORE_URLS
                        value: "http://+:80"
                      - name: MongoDbSettings__ConnectionString
                        value: "mongodb://MongoDb"
                      - name: RabbitMq__Host
                        value: "rabbitmq"
                - name: rabbitmq
                  image: rabbitmq
                  ports:
                      - containerPort: 80
                  env:
                      - name: ASPNETCORE_ENVIRONMENT
                        value: "Development"
                      - name: ASPNETCORE_URLS
                        value: "http://+:80"
                      - name: MongoDbSettings__ConnectionString
                        value: "mongodb://MongoDb"
                      - name: RabbitMq__Host
                        value: "rabbitmq"
                - name: mongodb
                  image: mongo
                  ports:
                        - containerPort: 80
                  env:
                      - name: ASPNETCORE_ENVIRONMENT
                        value: "Development"
                      - name: ASPNETCORE_URLS
                        value: "http://+:80"
                      - name: MongoDbSettings__ConnectionString
                        value: "mongodb://MongoDb"
                      - name: RabbitMq__Host
                        value: "rabbitmq"
                - name: acountdb
                  image: postgres
                  ports:
                            - containerPort: 80
                  env:
                      - name: ASPNETCORE_ENVIRONMENT
                        value: "Development"
                      - name: ASPNETCORE_URLS
                        value: "http://+:80"
                      - name: MongoDbSettings__ConnectionString
                        value: "mongodb://MongoDb"
                      - name: RabbitMq__Host
                        value: "rabbitmq"