x-environment: 
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres

services:
  accountservice:
    image: accountservice
    build:
      context: .
      dockerfile: AccountService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Server=AcountDb;Port=5432;Database=accountdb;Username=postgres;Password=postgres; 
    ports:
      - "5239:80"

  AcountDb:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - accountdb:/var/lib/postgresql/data
          
  MongoDb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=admin123
    ports:
      - "27017:27017"
    volumes:
      - mongodb:/data/db


volumes:
    accountdb:
    mongodb:
    